const axios = require('axios');
const cheerio = require('cheerio');
const fs = require('fs');

const API_BASE = 'https://th.wikisource.org/w/api.php';
const USER_AGENT = 'TammaAppBot/1.0 (https://kaisoft.net; admin@kaisoft.net) axios/1.0';

async function fetchCategoryMembers(category, limit = 20) {
  const url = `${API_BASE}?action=query&list=categorymembers&cmtitle=${encodeURIComponent(category)}&cmlimit=${limit}&format=json`;
  const res = await axios.get(url, { headers: { 'User-Agent': USER_AGENT } });
  return res.data.query.categorymembers;
}

async function fetchPageContent(pageId) {
  const url = `${API_BASE}?action=parse&pageid=${pageId}&prop=text&format=json`;
  const res = await axios.get(url, { headers: { 'User-Agent': USER_AGENT } });
  return res.data.parse.text['*'];
}

async function runScraper() {
  console.log('🔍 เริ่มต้นดึงข้อมูลบทสวดมนต์จาก Wikisource...');
  try {
    const members = await fetchCategoryMembers('Category:บทสวดมนต์', 30);
    console.log(`พบข้อมูล ${members.length} รายการ`);

    const scrapedPrayers = [];

    for (let i = 0; i < members.length; i++) {
      const page = members[i];
      // Skip subcategories or non-main namespace
      if (page.ns !== 0) continue;
      
      console.log(`[${i+1}/${members.length}] กำลังดึงเนื้อหา: ${page.title}`);
      
      try {
        const html = await fetchPageContent(page.pageid);
        const $ = cheerio.load(html);
        
        // Extract text, remove tables/navboxes which are usually metadata
        $('.navbox').remove();
        $('table').remove();
        
        // Extract plain text
        let text = $('.mw-parser-output').text();
        
        // Clean up the text
        text = text.replace(/\[แก้ไข\]/g, '')
                   .replace(/\[\d+\]/g, '')
                   .replace(/\n\s*\n/g, '\n\n')
                   .trim();
                   
        if (!text || text.length < 50) {
           console.log(`  -> ข้าม (เนื้อหาสั้นเกินไป)`);
           continue;
        }

        // Limit the text to avoid excessively long files
        if (text.length > 3000) {
           text = text.substring(0, 3000) + '...\n(เนื้อหาถูกตัดทอนเพื่อความเหมาะสมของแอป)';
        }

        // Formulate JSON structure
        const prayer = {
          id: `wiki-${page.pageid}`,
          title: page.title.replace('บทสวดมนต์ ', '').trim(),
          category: 'บทสวดมนต์ทั่วไป',
          author: 'วิกิซอร์ซ (Wikisource)',
          description: `แหล่งที่มา: Wikisource - ${page.title}`,
          status: 'approved',
          pages: [
            {
              pageNumber: 1,
              verseTitle: page.title,
              pali: text,
              thai: 'บทสวดจากคลังข้อมูลสาธารณะ Wikisource'
            }
          ]
        };
        
        scrapedPrayers.push(prayer);
        
        // Wait 500ms to be polite to Wikipedia API
        await new Promise(r => setTimeout(r, 500));
        
      } catch (err) {
        console.error(`  -> ข้อผิดพลาดในการดึงหน้า ${page.title}:`, err.message);
      }
    }

    console.log(`\n✅ ดึงข้อมูลสำเร็จทั้งหมด ${scrapedPrayers.length} บทสวด`);
    
    // Write to file
    const jsContent = `/**
 * Tamma OS - Scraped Buddhist Prayers from Wikisource
 * Auto-generated by scrape_wikipedia.js
 */

export const SCRAPED_PRAYERS = ${JSON.stringify(scrapedPrayers, null, 2)};
`;

    fs.writeFileSync('src/js/scraped-prayers.js', jsContent, 'utf8');
    console.log('💾 บันทึกไฟล์ src/js/scraped-prayers.js เรียบร้อยแล้ว');
    
  } catch (err) {
    console.error('❌ เกิดข้อผิดพลาดหลัก:', err.message);
  }
}

runScraper();
